#!/bin/bash
# Start June 2026 Trading Bot
# Trained on June 29-30 data from S3

echo "================================================================================"
echo "JUNE 2026 TRADING BOT"
echo "================================================================================"
echo ""
echo "Configuration: Top 5 Most Active June Categories"
echo "  1. KXBTC (Bitcoin): 84,839 June trades"
echo "  2. KXWCADVANCE (World Cup Advance): 68,295 June trades"
echo "  3. KXBTCD (Bitcoin Daily): 57,284 June trades"
echo "  4. KXWCGAME (World Cup Games): 23,280 June trades"
echo "  5. KXMLBGAME (MLB Games): 21,417 June trades"
echo ""
echo "Capital Allocation:"
echo "  Total Capital: \$95.37"
echo "  Per Category: \$19.07 (5 × \$19.07 = \$95.35)"
echo "  Reserve: ~\$5.00"
echo ""
echo "Training Data: June 29-30, 2026 (553k trades from S3)"
echo "Models: rl_bot/mm_checkpoints/june_{CATEGORY}_final.zip"
echo ""
echo "Key Improvements vs Top 50:"
echo "  ✅ Trained on CURRENT June data (not stale April data)"
echo "  ✅ Only ACTIVE categories (verified June trade volume)"
echo "  ✅ Higher capital per category (\$19.07 vs \$1.90)"
echo "  ✅ Current market conditions reflected in models"
echo ""
echo "Risk Management:"
echo "  Max inventory per category: 6 contracts"
echo "  Max total inventory: 20 contracts"
echo "  Quote size: 3 contracts"
echo "  Max daily loss: \$15.00"
echo ""
echo "================================================================================"
echo "Starting bot..."
echo ""

python -m rl_bot.live_trader_v2
