#!/bin/bash
# Start Top 50 Refined Trading Bot
# Highest-performing categories with optimal capital allocation

echo "================================================================================"
echo "TOP 50 REFINED DEPLOYMENT"
echo "================================================================================"
echo ""
echo "Strategy: Concentrated capital on best performers"
echo "  - 50 highest-performing categories (vs 262)"
echo "  - \$1.90 per category (vs \$0.35)"
echo "  - 5.4x more capital per category = overcome fee drag"
echo ""
echo "Selection Criteria:"
echo "  ✅ Top 50 by test PnL from temporal split"
echo "  ✅ Profitable on BOTH train + test"
echo "  ✅ Overfit ratio < 2x"
echo "  ✅ Live open markets on Kalshi"
echo ""
echo "Capital Allocation:"
echo "  Total Capital: \$95.37"
echo "  Per Category: \$1.90 (50 × \$1.90 = \$95.00)"
echo "  Reserve: ~\$5.00"
echo ""
echo "Risk Management:"
echo "  Max inventory per category: 4 contracts (vs 2)"
echo "  Max total inventory: 30 contracts (vs 20)"
echo "  Quote size: 2 contracts (vs 1)"
echo "  Max daily loss: \$12.00"
echo ""
echo "Why This Works Better:"
echo "  1. Higher capital overcomes \$0.01-0.05 fee drag"
echo "  2. Concentrated on proven winners only"
echo "  3. Better position sizing for profit potential"
echo "  4. Fewer positions = less dilution"
echo ""
echo "Top 10 Categories (by test PnL):"
echo "  1. KXLOLTOTALMAPS          \$14.14  (League of Legends)"
echo "  2. KXQUADRUPLEDOUBLE       \$10.35  (NBA stats)"
echo "  3. KXBBCHARTPOSITIONALBUM  \$10.10  (Billboard charts)"
echo "  4. KXSERIEABTTS            \$10.03  (Serie A soccer)"
echo "  5. KXWNBADELAY             \$9.84   (WNBA)"
echo "  6. KXNASCARRACE            \$9.82   (NASCAR)"
echo "  7. KXRAINLAXM              \$9.81   (Weather)"
echo "  8. KXCHESSWORLDCHAMPION    \$9.79   (Chess)"
echo "  9. KXF1CONSTRUCTORS        \$9.79   (Formula 1)"
echo " 10. KXHIGHAUS               \$9.79   (Politics)"
echo ""
echo "================================================================================"
echo "Starting bot..."
echo ""

python -m rl_bot.live_trader_v2
