#!/bin/bash
# Start 262 Temporal-Tested Categories Bot
# Consistent performers from HPC temporal split testing

echo "================================================================================"
echo "262 TEMPORAL-TESTED CATEGORIES DEPLOYMENT"
echo "================================================================================"
echo ""
echo "Categories: 262 consistent performers"
echo "  - Profitable on BOTH train + test splits"
echo "  - Overfit ratio < 2x (low overfitting)"
echo "  - Live open markets on Kalshi (verified)"
echo ""
echo "Testing Methodology:"
echo "  - Split: 70/30 temporal (Apr 18-22 train, Apr 23-25 test)"
echo "  - Algorithm: PPO, 500K timesteps"
echo "  - Subpenny: enabled (queue priority model)"
echo "  - Evaluation: 3 episodes per category per split"
echo ""
echo "Capital Allocation:"
echo "  Total Capital: \$91.66"
echo "  Active: ~\$86.66 (262 × \$0.35)"
echo "  Reserve: ~\$5.00"
echo ""
echo "Risk Management:"
echo "  Max inventory per category: 2 contracts"
echo "  Max total inventory: 20 contracts"
echo "  Max daily loss: \$10.00"
echo ""
echo "Top 10 Performers (by test PnL):"
echo "  1. KXLOLTOTALMAPS         \$14.14"
echo "  2. KXQUADRUPLEDOUBLE      \$10.35"
echo "  3. KXBBCHARTPOSITIONALBUM \$10.10"
echo "  4. KXSERIEABTTS           \$10.03"
echo "  5. KXWNBADELAY            \$9.84"
echo "  6. KXNASCARRACE           \$9.82"
echo "  7. KXRAINLAXM             \$9.81"
echo "  8. KXCHESSWORLDCHAMPION   \$9.79"
echo "  9. KXF1CONSTRUCTORS       \$9.79"
echo " 10. KXHIGHAUS             \$9.79"
echo ""
echo "================================================================================"
echo "Starting bot..."
echo ""

python -m rl_bot.live_trader_v2
