#!/bin/bash
# Submit all MM training jobs
set -euo pipefail

sbatch hpc/mm_jobs/mm_KXWCADVANCE.slurm
sbatch hpc/mm_jobs/mm_KXMVESPORTSMULTIGAMEEXTENDED.slurm
sbatch hpc/mm_jobs/mm_KXBTC15M.slurm
sbatch hpc/mm_jobs/mm_KXWCGAME.slurm
sbatch hpc/mm_jobs/mm_KXMLBGAME.slurm
sbatch hpc/mm_jobs/mm_KXBTCD.slurm
sbatch hpc/mm_jobs/mm_KXWCMOV.slurm
sbatch hpc/mm_jobs/mm_KXMVECROSSCATEGORY.slurm
sbatch hpc/mm_jobs/mm_KXWCSCORE.slurm
sbatch hpc/mm_jobs/mm_KXWCGOAL.slurm
sbatch hpc/mm_jobs/mm_KXATPCHALLENGERMATCH.slurm
sbatch hpc/mm_jobs/mm_KXWCTOTAL.slurm
sbatch hpc/mm_jobs/mm_KXETH15M.slurm
sbatch hpc/mm_jobs/mm_KXMLBTOTAL.slurm
sbatch hpc/mm_jobs/mm_KXWCBTTS.slurm
sbatch hpc/mm_jobs/mm_KXITFMATCH.slurm
sbatch hpc/mm_jobs/mm_KXWCMENTION.slurm
sbatch hpc/mm_jobs/mm_KXMLBSPREAD.slurm
sbatch hpc/mm_jobs/mm_KXDOGE15M.slurm
sbatch hpc/mm_jobs/mm_KXSOL15M.slurm
sbatch hpc/mm_jobs/mm_KXBNB15M.slurm
sbatch hpc/mm_jobs/mm_KXXRP15M.slurm
sbatch hpc/mm_jobs/mm_KXWCTCORNERS.slurm
sbatch hpc/mm_jobs/mm_KXMENWORLDCUP.slurm
sbatch hpc/mm_jobs/mm_KXWC2H.slurm
sbatch hpc/mm_jobs/mm_KXWCSPREAD.slurm
sbatch hpc/mm_jobs/mm_KXHYPE15M.slurm
sbatch hpc/mm_jobs/mm_KXITFWMATCH.slurm
sbatch hpc/mm_jobs/mm_KXWCCORNERS.slurm
sbatch hpc/mm_jobs/mm_KXWCMOF.slurm
sbatch hpc/mm_jobs/mm_KXWCTEAMTOTAL.slurm
sbatch hpc/mm_jobs/mm_KXBTC.slurm
sbatch hpc/mm_jobs/mm_KXWCSOA.slurm
sbatch hpc/mm_jobs/mm_KXETHD.slurm
sbatch hpc/mm_jobs/mm_KXWC1H.slurm
sbatch hpc/mm_jobs/mm_KXWC1HSCORE.slurm
sbatch hpc/mm_jobs/mm_KXMLBHR.slurm
sbatch hpc/mm_jobs/mm_KXMLBRFI.slurm
sbatch hpc/mm_jobs/mm_KXMLBF5.slurm
sbatch hpc/mm_jobs/mm_KXMLBF5TOTAL.slurm
sbatch hpc/mm_jobs/mm_KXWC1HBTTS.slurm
sbatch hpc/mm_jobs/mm_KXWC1HTOTAL.slurm
sbatch hpc/mm_jobs/mm_KXATPMATCH.slurm
sbatch hpc/mm_jobs/mm_KXWCROUND.slurm
sbatch hpc/mm_jobs/mm_KXMLBKS.slurm
sbatch hpc/mm_jobs/mm_KXWCFTTS.slurm
sbatch hpc/mm_jobs/mm_KXWC2HTOTAL.slurm
sbatch hpc/mm_jobs/mm_KXMLBTEAMTOTAL.slurm
sbatch hpc/mm_jobs/mm_KXWCAST.slurm
sbatch hpc/mm_jobs/mm_KXWC2HBTTS.slurm
sbatch hpc/mm_jobs/mm_KXSOLD.slurm
sbatch hpc/mm_jobs/mm_KXCS2GAME.slurm
sbatch hpc/mm_jobs/mm_KXMLBHIT.slurm
sbatch hpc/mm_jobs/mm_KXNEXTTEAMNBA.slurm
sbatch hpc/mm_jobs/mm_KXPGATOUR.slurm
sbatch hpc/mm_jobs/mm_KXMLBHRR.slurm
sbatch hpc/mm_jobs/mm_KXMLBF5SPREAD.slurm
sbatch hpc/mm_jobs/mm_KXWCSTAGEOFELIM.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTSFO.slurm
sbatch hpc/mm_jobs/mm_KXMLBTB.slurm
sbatch hpc/mm_jobs/mm_KXLOVEISLMENTION.slurm
sbatch hpc/mm_jobs/mm_KXWTAMATCH.slurm
sbatch hpc/mm_jobs/mm_KXWCFIRSTGOAL.slurm
sbatch hpc/mm_jobs/mm_KXLIUSACOUPLE.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTSEA.slurm
sbatch hpc/mm_jobs/mm_KXMADDOWMENTION.slurm
sbatch hpc/mm_jobs/mm_KXWC1HSPREAD.slurm
sbatch hpc/mm_jobs/mm_KXWC2HSPREAD.slurm
sbatch hpc/mm_jobs/mm_KXTESTMATCH.slurm
sbatch hpc/mm_jobs/mm_KXHIGHLAX.slurm
sbatch hpc/mm_jobs/mm_KXRANKLISTSONGSPOTUSA.slurm
sbatch hpc/mm_jobs/mm_KXLIUSAELIMINATIONW.slurm
sbatch hpc/mm_jobs/mm_KXAAAGASD.slurm
sbatch hpc/mm_jobs/mm_KXXRPD.slurm
sbatch hpc/mm_jobs/mm_KXWCFURTHESTADVANCING.slurm
sbatch hpc/mm_jobs/mm_KXHIGHDEN.slurm
sbatch hpc/mm_jobs/mm_KXWTI.slurm
sbatch hpc/mm_jobs/mm_KXHIGHCHI.slurm
sbatch hpc/mm_jobs/mm_KXLIUSAELIMINATION.slurm
sbatch hpc/mm_jobs/mm_KXWNBAGAME.slurm
sbatch hpc/mm_jobs/mm_KXLOWTMIA.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTPHX.slurm
sbatch hpc/mm_jobs/mm_KXUFCFIGHT.slurm
sbatch hpc/mm_jobs/mm_KXATP.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTLV.slurm
sbatch hpc/mm_jobs/mm_KXCS2MAP.slurm
sbatch hpc/mm_jobs/mm_KXMUSKNW.slurm
sbatch hpc/mm_jobs/mm_KXTRUMPADMINLEAVE.slurm
sbatch hpc/mm_jobs/mm_KXAAAGASM.slurm
sbatch hpc/mm_jobs/mm_KXLOLGAME.slurm
sbatch hpc/mm_jobs/mm_KXHIGHNY.slurm
sbatch hpc/mm_jobs/mm_KXMLBMENTION.slurm
sbatch hpc/mm_jobs/mm_KXRT.slurm
sbatch hpc/mm_jobs/mm_KXWCFIRSTSONG.slurm
sbatch hpc/mm_jobs/mm_KXWCGOALLEADER.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTMIN.slurm
sbatch hpc/mm_jobs/mm_KXTRUMPSAY.slurm
sbatch hpc/mm_jobs/mm_KXTEMPNYCH.slurm
sbatch hpc/mm_jobs/mm_KXPGATOP20.slurm
sbatch hpc/mm_jobs/mm_KXETH.slurm
sbatch hpc/mm_jobs/mm_KXWCTEAMH2H.slurm
sbatch hpc/mm_jobs/mm_KXEARNINGSMENTIONAVAV.slurm
sbatch hpc/mm_jobs/mm_KXLOVEISLANDUSARANK.slurm
sbatch hpc/mm_jobs/mm_KXWT20MATCH.slurm
sbatch hpc/mm_jobs/mm_KXLOWTSATX.slurm
sbatch hpc/mm_jobs/mm_KXGTAPREORDERS.slurm
sbatch hpc/mm_jobs/mm_KXBNBD.slurm
sbatch hpc/mm_jobs/mm_KXNBA.slurm
sbatch hpc/mm_jobs/mm_KXWCAWARD.slurm
sbatch hpc/mm_jobs/mm_KXTRUMPSAYMONTH.slurm
sbatch hpc/mm_jobs/mm_KXNATGASD.slurm
sbatch hpc/mm_jobs/mm_KXHIGHAUS.slurm
sbatch hpc/mm_jobs/mm_KXTRUMPSAYNICKNAME.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTDC.slurm
sbatch hpc/mm_jobs/mm_KXWCTEAMFIRSTGOAL.slurm
sbatch hpc/mm_jobs/mm_KXHYPED.slurm
sbatch hpc/mm_jobs/mm_KXHIGHTSATX.slurm
sbatch hpc/mm_jobs/mm_KXALBUMEQUIV.slurm
sbatch hpc/mm_jobs/mm_KXSILVERW.slurm
sbatch hpc/mm_jobs/mm_KXSPACEXCOUNT.slurm
sbatch hpc/mm_jobs/mm_KXLOWTMIN.slurm
sbatch hpc/mm_jobs/mm_KXHIGHPHIL.slurm
sbatch hpc/mm_jobs/mm_KX14AMENDCASE.slurm
sbatch hpc/mm_jobs/mm_KXGOLDD.slurm
sbatch hpc/mm_jobs/mm_KXAPRPOTUS.slurm
sbatch hpc/mm_jobs/mm_KXVALORANTGAME.slurm
sbatch hpc/mm_jobs/mm_KXNASCARRACE.slurm
sbatch hpc/mm_jobs/mm_KXLATENIGHTMENTION.slurm
sbatch hpc/mm_jobs/mm_KXMLBRBI.slurm
sbatch hpc/mm_jobs/mm_KXBSNGAME.slurm

echo "Submitted 130 jobs"
