"""
262 Live Tradeable Categories from Temporal Split Testing
Consistent performers: profitable on both train+test, overfit < 2x, open markets on Kalshi

Based on: hpc/mm_temporal_split_results.md
Split: 70/30 temporal (April 18-22 train, April 23-25 test)
Algorithm: PPO, 500K timesteps, subpenny enabled
"""

from dataclasses import dataclass
from typing import List

@dataclass
class CategoryConfig:
    """Configuration for a single category."""
    name: str
    max_contracts: int = 1
    max_inventory: int = 2  # Conservative for 262 categories
    capital_allocation: float = 0.35  # $91.66 / 262 = ~$0.35 per category
    test_pnl: float = 0.0

# All 416 consistent performers with live markets
TESTED_262_CATEGORIES = [
    CategoryConfig(
        name="KXLOLTOTALMAPS",
        test_pnl=14.14,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXQUADRUPLEDOUBLE",
        test_pnl=10.35,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBBCHARTPOSITIONALBUM",
        test_pnl=10.10,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSERIEABTTS",
        test_pnl=10.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXWNBADELAY",
        test_pnl=9.84,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNASCARRACE",
        test_pnl=9.82,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXRAINLAXM",
        test_pnl=9.81,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCHESSWORLDCHAMPION",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXF1CONSTRUCTORS",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHAUS",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAMVP",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTTEAMNFL",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLDRAFTOL",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLDRAFTPICK",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLHART",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSPOTIFYW",
        test_pnl=9.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXINXY",
        test_pnl=9.78,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLDRAFT1ST",
        test_pnl=9.78,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPRIMARYMOV",
        test_pnl=9.78,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLSCUP",
        test_pnl=9.65,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNCAAF",
        test_pnl=9.59,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXOSCARPIC",
        test_pnl=9.59,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSPOTIFYARTISTW",
        test_pnl=9.59,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEXPELSWALWELLVOTES",
        test_pnl=9.57,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXGREENLANDPRICE",
        test_pnl=9.55,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBALLONDOR",
        test_pnl=9.52,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXU3MAX",
        test_pnl=9.50,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDSENATESEATS",
        test_pnl=9.49,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMOCTRUMP25",
        test_pnl=9.45,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSB",
        test_pnl=9.39,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXETHMINMON",
        test_pnl=9.38,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAFINMVP",
        test_pnl=9.38,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPGAR3LEAD",
        test_pnl=9.38,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTEAMSINSC",
        test_pnl=9.32,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNETFLIXRANKSHOWGLOBAL",
        test_pnl=9.30,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBTCY",
        test_pnl=9.28,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPGAR1LEAD",
        test_pnl=9.27,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLB",
        test_pnl=9.25,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNETFLIXRANKSHOWGLOBAL2",
        test_pnl=9.25,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPRESPERSON",
        test_pnl=9.23,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTTEAMNBA",
        test_pnl=9.21,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCOACHOUTNFL",
        test_pnl=9.18,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA3D",
        test_pnl=9.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXVISITIRAN",
        test_pnl=9.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMARMAD",
        test_pnl=9.15,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDHOUSESEATS",
        test_pnl=9.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNCAAMBNEXTCOACH",
        test_pnl=9.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMADMEN",
        test_pnl=9.11,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA1STTEAMDEF",
        test_pnl=9.11,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXECONSTATCPI",
        test_pnl=9.05,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLTEAM1POS",
        test_pnl=9.04,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXROLEATEVENTLOLLA",
        test_pnl=8.99,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHEISMAN",
        test_pnl=8.98,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBAL",
        test_pnl=8.98,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLNORRIS",
        test_pnl=8.94,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLFIRSTGOAL",
        test_pnl=8.91,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDOGEMAX1",
        test_pnl=8.90,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPIRAN",
        test_pnl=8.88,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBARETURN",
        test_pnl=8.83,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBBESTRECORD",
        test_pnl=8.78,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXKPOPDH2",
        test_pnl=8.76,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSOLMAXMON",
        test_pnl=8.76,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXXRPMAXMON",
        test_pnl=8.75,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBTCMAX150",
        test_pnl=8.70,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCAGOVPRIMARY1ST",
        test_pnl=8.67,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPBULLCASECOMBO",
        test_pnl=8.65,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPGAR2LEAD",
        test_pnl=8.64,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTOPARTISTUSA",
        test_pnl=8.63,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXAMERICANIDOL",
        test_pnl=8.59,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAOVERTIME",
        test_pnl=8.57,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFOWOMEN",
        test_pnl=8.50,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTISRAELPM",
        test_pnl=8.50,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXWCGOALLEADER",
        test_pnl=8.50,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLEAVEWALZ",
        test_pnl=8.48,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTOPCHEF",
        test_pnl=8.45,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXWNBA",
        test_pnl=8.44,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTARIFFCHECKS",
        test_pnl=8.39,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBATOPPICK",
        test_pnl=8.37,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCONNSMYTHE",
        test_pnl=8.36,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSCOTTIESLAM",
        test_pnl=8.36,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBOYCOTTWC",
        test_pnl=8.35,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXELONMARS",
        test_pnl=8.35,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBALCY",
        test_pnl=8.23,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBNL",
        test_pnl=8.23,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA1HSPREAD",
        test_pnl=8.23,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMEDIARELEASEST",
        test_pnl=8.17,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDOGEMAXMON",
        test_pnl=8.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTMANAGERMANU",
        test_pnl=8.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPAHLAVIHEAD",
        test_pnl=8.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTNBACOACH",
        test_pnl=8.09,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTIME",
        test_pnl=8.09,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEUROVISION",
        test_pnl=8.06,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA1HWINNER",
        test_pnl=8.06,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXIRANDEMOCRACY",
        test_pnl=8.04,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPSASQUASH",
        test_pnl=8.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXVPRESNOMD",
        test_pnl=8.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KX14AMENDCASE",
        test_pnl=7.98,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEWDEAL",
        test_pnl=7.97,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBALWEST",
        test_pnl=7.83,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXGOVCAPRIMARY",
        test_pnl=7.82,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLPGATOUR",
        test_pnl=7.82,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAMIMP",
        test_pnl=7.81,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLSERIESSPREAD",
        test_pnl=7.78,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXANIMEAOTY",
        test_pnl=7.66,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBASWEEP",
        test_pnl=7.61,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPEARLMANMENTION",
        test_pnl=7.57,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="TESLACEOCHANGE",
        test_pnl=7.56,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLAFCCHAMP",
        test_pnl=7.49,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMEDIARELEASEICEMAN",
        test_pnl=7.48,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXF1RACE",
        test_pnl=7.43,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFACUP",
        test_pnl=7.43,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXETHY",
        test_pnl=7.40,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPMEET",
        test_pnl=7.39,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRYFIREPOWELL",
        test_pnl=7.39,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCOREUND",
        test_pnl=7.36,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBAWARDCOMBO",
        test_pnl=7.36,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXRAINDENM",
        test_pnl=7.35,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMOVIEDELAYODYSSEY",
        test_pnl=7.34,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPPHOTO",
        test_pnl=7.32,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBALMVP",
        test_pnl=7.29,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLALIGASPREAD",
        test_pnl=7.27,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMILLSDROPOUT",
        test_pnl=7.18,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCCLIMIT",
        test_pnl=7.14,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXRETIREPELOSI",
        test_pnl=7.14,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLIGUE1SPREAD",
        test_pnl=7.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFEDMEET",
        test_pnl=7.08,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPBEARCASECOMBO",
        test_pnl=7.07,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLDRAFTEDGE",
        test_pnl=7.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBADRAFT1",
        test_pnl=7.02,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXUSAEXPANDTERRITORY",
        test_pnl=7.02,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXWTIMIN",
        test_pnl=7.01,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXETHMAXMON",
        test_pnl=6.96,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCAGOVMATCHUP",
        test_pnl=6.95,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXIRANEMBASSY",
        test_pnl=6.94,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNCAAMBAPRANK",
        test_pnl=6.89,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBATEAMTOTAL",
        test_pnl=6.86,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXARREST",
        test_pnl=6.84,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXRANKLISTGOOGLESEARCH",
        test_pnl=6.84,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXELECTIRAN",
        test_pnl=6.82,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXGOVWINOMD",
        test_pnl=6.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFOMEN",
        test_pnl=6.76,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNETANYAHUPARDON",
        test_pnl=6.73,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSPACEXSTARSHIP",
        test_pnl=6.63,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNASCARCUPSERIES",
        test_pnl=6.59,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNCAABASEBALL",
        test_pnl=6.58,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSERIEA1H",
        test_pnl=6.57,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXXRPMINMON",
        test_pnl=6.57,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBESTLLMCHINA",
        test_pnl=6.53,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHPHIL",
        test_pnl=6.53,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHTLV",
        test_pnl=6.53,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHTMIN",
        test_pnl=6.53,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHTNOLA",
        test_pnl=6.53,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOWTNYC",
        test_pnl=6.53,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHTDC",
        test_pnl=6.51,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOWTATL",
        test_pnl=6.50,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHORMUZWEEKLY",
        test_pnl=6.49,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPCRYPTOCONF",
        test_pnl=6.49,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBNLROTY",
        test_pnl=6.48,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTOPMODEL",
        test_pnl=6.48,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEFLCHAMPIONSHIPSPREAD",
        test_pnl=6.47,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEKSTRAKLASAGAME",
        test_pnl=6.46,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSWIFTKELCEWEDDINGLOCATION",
        test_pnl=6.45,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCOPADOBRASILSPREAD",
        test_pnl=6.43,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAWEST",
        test_pnl=6.43,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLUTNICKOUT",
        test_pnl=6.42,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSURVIVORMENTION",
        test_pnl=6.39,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBNLWEST",
        test_pnl=6.37,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTEAMSINNBAWF",
        test_pnl=6.35,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEARTHQUAKECALIFORNIA",
        test_pnl=6.34,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXIPHONERELEASE",
        test_pnl=6.34,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXUFCVICROUND",
        test_pnl=6.34,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLDRAFTTEAM",
        test_pnl=6.32,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCHLLDPGAME",
        test_pnl=6.29,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAEFINMVP",
        test_pnl=6.26,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDFBPOKALSPREAD",
        test_pnl=6.24,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMVESPORTSMULTIGAMEEXTENDED",
        test_pnl=6.24,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXUSACOMPANYSTAKE",
        test_pnl=6.21,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOWTPHIL",
        test_pnl=6.19,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCABOUT",
        test_pnl=6.18,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSPOTIFYGLOBALD",
        test_pnl=6.18,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXVPRESNOMR",
        test_pnl=6.18,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXROASTSUBJECT",
        test_pnl=6.17,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSCOTUSMARIJUANAGUN",
        test_pnl=6.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPAHLAVIVISITA",
        test_pnl=6.15,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXYOUTHUN",
        test_pnl=6.15,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFM30YMTG",
        test_pnl=6.14,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTLEVELCHEF",
        test_pnl=6.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXRETIREMM",
        test_pnl=6.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTX18D",
        test_pnl=6.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAWFINMVP",
        test_pnl=6.11,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSNLHOST",
        test_pnl=6.10,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTEAMSINNBAF",
        test_pnl=6.05,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXGAMEAWARDS",
        test_pnl=6.04,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXIMPEACHCABINET",
        test_pnl=6.02,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXVISITVENEZUELA",
        test_pnl=6.02,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCARDPRESENCEUFCWH",
        test_pnl=6.01,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTMANAGERLALIGA",
        test_pnl=6.01,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMVECROSSCATEGORY",
        test_pnl=5.97,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFEDDISSENT",
        test_pnl=5.95,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNY12D",
        test_pnl=5.95,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMENWORLDCUP",
        test_pnl=5.89,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLDRAFTQB",
        test_pnl=5.89,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXWTIMINM",
        test_pnl=5.89,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXGTATRAILER",
        test_pnl=5.84,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNEXTAG",
        test_pnl=5.81,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLSERIESSCORE",
        test_pnl=5.81,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="MOON",
        test_pnl=5.79,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPRESNOMD",
        test_pnl=5.76,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="TESLAOPTIMUS",
        test_pnl=5.75,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMEDIACOVERMADDEN",
        test_pnl=5.74,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTAKEOVERACQWB",
        test_pnl=5.73,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBNLCY",
        test_pnl=5.72,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXVAHOUSEDEM",
        test_pnl=5.70,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNETFLIXRANKMOVIERUNNERUP",
        test_pnl=5.68,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTOPMONTHLY",
        test_pnl=5.68,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXAGNOMTXR",
        test_pnl=5.55,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTECHRANKLISTAICODE",
        test_pnl=5.55,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBOND",
        test_pnl=5.54,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBASERIESSCORE",
        test_pnl=5.54,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXRHOUSESEATS",
        test_pnl=5.54,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPS6",
        test_pnl=5.52,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA2HTOTAL",
        test_pnl=5.50,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXGOLFMAJORS",
        test_pnl=5.49,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOWTNOLA",
        test_pnl=5.49,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBTCMAXY",
        test_pnl=5.47,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXALITOOUT",
        test_pnl=5.43,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFOMCDISSENTCOUNT",
        test_pnl=5.41,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBWORSTRECORD",
        test_pnl=5.41,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA2HWINNER",
        test_pnl=5.38,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRDBAN",
        test_pnl=5.38,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPPARDON",
        test_pnl=5.36,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOWTSEA",
        test_pnl=5.34,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSTATEMENTCOUNTEARLE",
        test_pnl=5.33,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXCOPADOBRASILGAME",
        test_pnl=5.32,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBNLEAST",
        test_pnl=5.31,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="FEDHIKE",
        test_pnl=5.24,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDHSCOMPONENT",
        test_pnl=5.19,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLADAMS",
        test_pnl=5.17,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXECONSTATCPIYOY",
        test_pnl=5.16,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXBOLPDIVGAME",
        test_pnl=5.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXSENATEKYR",
        test_pnl=5.12,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXFEDERALCHARGE",
        test_pnl=5.11,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOSEPRIMARYSENATER",
        test_pnl=5.11,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNHLWEST",
        test_pnl=5.09,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEPL1H",
        test_pnl=5.08,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBAEAST",
        test_pnl=5.06,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTNOTED",
        test_pnl=5.06,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNBA1STTEAM",
        test_pnl=5.05,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHIGHTPHX",
        test_pnl=5.04,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXLOWTAUS",
        test_pnl=5.04,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDIAZOUT",
        test_pnl=5.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXMLBPLAYEROTM",
        test_pnl=5.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXVANCEPAKISTAN",
        test_pnl=5.03,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXDASHORDERS",
        test_pnl=4.99,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNFLNFCSOUTH",
        test_pnl=4.99,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXPGAMAJORWIN",
        test_pnl=4.97,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTRUMPREMOVE",
        test_pnl=4.92,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXB200W",
        test_pnl=4.90,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXHMONTH",
        test_pnl=4.87,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXEFLCHAMPIONSHIPGAME",
        test_pnl=4.84,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXTXRSENRUNOFFMOV",
        test_pnl=4.84,
        capital_allocation=0.35
    ),
    CategoryConfig(
        name="KXNASCARTOP3",
        test_pnl=4.80,
        capital_allocation=0.35
    ),
]

# Calculate allocation
TOTAL_ALLOCATION = sum(cat.capital_allocation for cat in TESTED_262_CATEGORIES)
RESERVE_CAPITAL = max(91.66 - TOTAL_ALLOCATION, 5.00)  # Keep at least $5 reserve

# Trading configuration
TRADING_CONFIG = {
    "mode": "live",
    "capital": 91.66,
    "reserve": "RESERVE_CAPITAL",
    "active_capital": "min(TOTAL_ALLOCATION, 86.66)",

    # Global limits - Conservative
    "max_daily_loss": 10.00,
    "max_position_value": 60.00,
    "stop_loss_threshold": -20.00,

    # Execution - Subpenny enabled (as in testing)
    "subpenny_enabled": True,
    "quote_offset_bid": +0.001,
    "quote_offset_ask": -0.001,
    "quote_size": 1,

    # Risk management - Very conservative with 262 markets
    "max_inventory_per_category": 2,
    "max_total_inventory": 20,
    "halt_on_consecutive_losses": 3,

    # Categories
    "categories": TESTED_262_CATEGORIES,
}

# Monitoring configuration
MONITORING_CONFIG = {
    "alert_on_daily_loss": 6.00,
    "alert_on_stop_loss": -20.00,
    "alert_on_fill_rate_drop": 0.05,
    "alert_on_websocket_downtime": 60,

    # Logging
    "log_all_quotes": False,  # Too noisy with 262 markets
    "log_all_fills": True,
    "log_all_orders": True,
    "log_pnl_updates": True,

    # Reports
    "daily_report_enabled": True,
    "hourly_summary_enabled": False,
}
